#!/usr/bin/env bash

: '
    Serves HTML content using Ktor.
'

source ../common

function printUsageAndExit { logError "Usage: 'serve $(blue "CONFIG_FILE")'"; exit 1; }

# Check that we have a single argument
if [[ $# -ne 1 ]]; then printUsageAndExit; fi
CONFIG_FILE="${1}" && readonly CONFIG_FILE
# Check that the provided configuration file argument value exists
if [[ ! -f $CONFIG_FILE ]]; then
  logError "Configuration file $(sQuote "$(red "${CONFIG_FILE}")") inaccessible or nonexistent." && printUsageAndExit
fi

ERRORS=0
# Ensure that Java is installed
java -version &>/dev/null || { ERRORS=1 && logError "Java not found on the system." ; }
# Ensure that jq installed
jq --version &>/dev/null || { ERRORS=1 && logError "$(sQuote "$(red "jq")") command not found." ; }
# If there's any error, exit
if [ "$ERRORS" -ne "0" ]; then
  logError "Exiting due to previous errors."; exit 1
else
  # Read the configuration file's identity
  ID=$(jq -r '.id' "${CONFIG_FILE}") && readonly ID
  # Some initial user feedback
  logInfo "Using the $(sQuote "$(blue "${ID}")") configuration."

  # Output the current Java version we will be using
  java -version && logInfo "Press $(green "ctrl+d") to stop the server"

  # Start the Ktor server
  ./gradlew run -Dio.github.learnyouahaskell.test.config="${CONFIG_FILE}"
fi